services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    # volumes:
    #   - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  worker:
    build: .
    command: rq worker
    deploy:
      replicas: 5
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis